PY?=python3
TMPDIR?=/tmp
CYCLE_ID?=CHIMERA-V2-RESEARCH-AND-EXECUTION-2026-02-15
STATUS_DATE?=2026-02-15
SNAPSHOT_ID?=local-cp4-status
CP4_STATUS_OUTPUT?=docs/policy/CHIMERA_V2_CP4_STATUS_AUTOGENERATED_$(STATUS_DATE).md
TREND_OUTPUT?=artifacts/ci/policy_trend_$(SNAPSHOT_ID).json
POLICY_PIPELINE_SUMMARY?=artifacts/ci/policy_pipeline_summary.json

.PHONY: install install-dev fmt lint type test check policy-gate policy-gate-negative cp3-readiness cp3-fixtures cp4-status generated-artifacts-shape

install:
	$(PY) -m pip install -r requirements.txt

install-dev: install
	$(PY) -m pip install -r requirements-dev.txt

fmt:
	$(PY) -m black gateway tests

lint:
	$(PY) -m ruff check gateway tests

type:
	$(PY) -m mypy gateway

test:
	TMPDIR=$(TMPDIR) $(PY) -m pytest

check: fmt lint type test policy-gate policy-gate-negative cp3-readiness

.PHONY: openapi
openapi:
	$(PY) scripts/export_openapi.py

.PHONY: grpc
grpc:
	$(PY) -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. artifacts/api/homegateway.proto

policy-gate:
	$(PY) scripts/evaluate_policy_gate.py --envelope artifacts/policy/envelope_r1_composition_example.json
	$(PY) scripts/evaluate_policy_gate.py --envelope artifacts/policy/envelope_r2_maelstrom_canary_example.json

policy-gate-negative:
	$(PY) scripts/check_policy_gate_negative.py

cp3-readiness:
	$(PY) scripts/evaluate_cp3_readiness.py --metrics artifacts/policy/cp3_readiness_metrics_example.json --output artifacts/policy/cp3_readiness_report_example.json

cp3-fixtures:
	$(PY) scripts/generate_cp3_metric_fixtures.py --output-dir artifacts/policy

cp4-status:
	$(PY) scripts/run_policy_pipeline.py --cycle-id "$(CYCLE_ID)" --date "$(STATUS_DATE)" --snapshot-id "$(SNAPSHOT_ID)" --metrics artifacts/policy/cp3_readiness_metrics_example.json --cp3-report artifacts/policy/cp3_readiness_report_example.json --trend-output "$(TREND_OUTPUT)" --status-output "$(CP4_STATUS_OUTPUT)" --summary-output "$(POLICY_PIPELINE_SUMMARY)" --strict
	$(PY) scripts/check_generated_artifact_shapes.py --cp3-report artifacts/policy/cp3_readiness_report_example.json --trend-glob "$(TREND_OUTPUT)"

generated-artifacts-shape:
	$(PY) scripts/check_generated_artifact_shapes.py --cp3-report artifacts/policy/cp3_readiness_report_example.json --trend-glob "artifacts/ci/policy_trend_*.json"
