# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from artifacts.api import homegateway_pb2 as artifacts_dot_api_dot_homegateway__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in artifacts/api/homegateway_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MyFortressStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/homegateway.v1.MyFortress/Health",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.Empty.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.ProbeHomeMerlin = channel.unary_unary(
            "/homegateway.v1.MyFortress/ProbeHomeMerlin",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinProbeRequest.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinProbeResponse.FromString,
            _registered_method=True,
        )
        self.HomeMerlinService = channel.unary_unary(
            "/homegateway.v1.MyFortress/HomeMerlinService",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinServiceRequest.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinServiceResponse.FromString,
            _registered_method=True,
        )
        self.HomeMerlinState = channel.unary_unary(
            "/homegateway.v1.MyFortress/HomeMerlinState",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinStateRequest.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinStateResponse.FromString,
            _registered_method=True,
        )
        self.ProbeFrigate = channel.unary_unary(
            "/homegateway.v1.MyFortress/ProbeFrigate",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.FrigateProbeRequest.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.FrigateProbeResponse.FromString,
            _registered_method=True,
        )
        self.FrigateEvents = channel.unary_unary(
            "/homegateway.v1.MyFortress/FrigateEvents",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.FrigateEventsRequest.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.FrigateEventsResponse.FromString,
            _registered_method=True,
        )
        self.Snapshot = channel.unary_unary(
            "/homegateway.v1.MyFortress/Snapshot",
            request_serializer=artifacts_dot_api_dot_homegateway__pb2.SnapshotRequest.SerializeToString,
            response_deserializer=artifacts_dot_api_dot_homegateway__pb2.SnapshotResponse.FromString,
            _registered_method=True,
        )


class MyFortressServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProbeHomeMerlin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HomeMerlinService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HomeMerlinState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProbeFrigate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FrigateEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MyFortressServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.Empty.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.HealthResponse.SerializeToString,
        ),
        "ProbeHomeMerlin": grpc.unary_unary_rpc_method_handler(
            servicer.ProbeHomeMerlin,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinProbeRequest.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinProbeResponse.SerializeToString,
        ),
        "HomeMerlinService": grpc.unary_unary_rpc_method_handler(
            servicer.HomeMerlinService,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinServiceRequest.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinServiceResponse.SerializeToString,
        ),
        "HomeMerlinState": grpc.unary_unary_rpc_method_handler(
            servicer.HomeMerlinState,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinStateRequest.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.HomeMerlinStateResponse.SerializeToString,
        ),
        "ProbeFrigate": grpc.unary_unary_rpc_method_handler(
            servicer.ProbeFrigate,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.FrigateProbeRequest.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.FrigateProbeResponse.SerializeToString,
        ),
        "FrigateEvents": grpc.unary_unary_rpc_method_handler(
            servicer.FrigateEvents,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.FrigateEventsRequest.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.FrigateEventsResponse.SerializeToString,
        ),
        "Snapshot": grpc.unary_unary_rpc_method_handler(
            servicer.Snapshot,
            request_deserializer=artifacts_dot_api_dot_homegateway__pb2.SnapshotRequest.FromString,
            response_serializer=artifacts_dot_api_dot_homegateway__pb2.SnapshotResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "homegateway.v1.MyFortress", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "homegateway.v1.MyFortress", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MyFortress(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/Health",
            artifacts_dot_api_dot_homegateway__pb2.Empty.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ProbeHomeMerlin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/ProbeHomeMerlin",
            artifacts_dot_api_dot_homegateway__pb2.HomeMerlinProbeRequest.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.HomeMerlinProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HomeMerlinService(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/HomeMerlinService",
            artifacts_dot_api_dot_homegateway__pb2.HomeMerlinServiceRequest.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.HomeMerlinServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HomeMerlinState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/HomeMerlinState",
            artifacts_dot_api_dot_homegateway__pb2.HomeMerlinStateRequest.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.HomeMerlinStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ProbeFrigate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/ProbeFrigate",
            artifacts_dot_api_dot_homegateway__pb2.FrigateProbeRequest.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.FrigateProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FrigateEvents(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/FrigateEvents",
            artifacts_dot_api_dot_homegateway__pb2.FrigateEventsRequest.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.FrigateEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Snapshot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/homegateway.v1.MyFortress/Snapshot",
            artifacts_dot_api_dot_homegateway__pb2.SnapshotRequest.SerializeToString,
            artifacts_dot_api_dot_homegateway__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
